"""After tests

Revision ID: 68f25fc02f05
Revises: eee3de9766ed
Create Date: 2020-07-31 16:35:42.420043

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "68f25fc02f05"
down_revision = "eee3de9766ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
