CREATE DATABASE users;
CREATE DATABASE mails;
CREATE DATABASE monitoring;
GRANT ALL PRIVILEGES ON DATABASE users TO postgres;
GRANT ALL PRIVILEGES ON DATABASE mails TO postgres;
GRANT ALL PRIVILEGES ON DATABASE monitoring TO postgres;
